name: deploy
run-name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.LAMBDA_DEPLOY_ROLE }}
        aws-region: us-east-1
    - name: Zip and Upload Lambda
      run: |
        zip -r function.zip blog_agent.py liteflow.py workflow.py tasks -x "*__pycache__*"
        aws lambda update-function-code --function-name blog-agent --zip-file fileb://function.zip --query LastUpdateStatus
      shell: bash
